<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function getLastNews()
    {
        return $this->createQueryBuilder('n')
                    ->where('n.isPublished = 1')
                    ->orderBy('n.publishedAt', 'DESC')
                    ->setMaxResults(4)
                    ->getQuery()
                    ->getResult();
    }
}
